### PR TITLE
Application for cancellation

### PR DESCRIPTION
**Pull request by leonelmunozlopez**
Docs for "Cancellation" transaction based on https://www.dropbox.com/s/m9z00381cex79yv/MANUAL%20POS%20INTEGRADO%20version%203.0.pdf?dl=0

Pages : 10, 26 (from)

### CODE REVIEW

**Comment by ffiebig** [comment]
Just one question, I wonder why it is called cancellation instead of void which is more common ?

**Comment by leonelmunozlopez** [comment]
> Just one question, I wonder why it is called cancellation instead of void which is more common ?

As translation for "Anulación or Solicitud de Anulación" is more common to say "cancellation of sale" or "transaction cancellation"

**Comment by ffiebig** [comment]
Translating directly can cause problems, in this context void is more widely used

**Comment by afiebig** [comment]
Hi, sorry to bringing this back to life, but seems to me that "Refund" is a good name for this method.

**Pull request merged**
